name: Daily Commit

on:
  schedule:
    - cron: "0 0 * * *"  # otomatis setiap hari jam 00:00 UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update file
        run: echo "Updated at $(date)" >> update.txt

      - name: Commit changes
        run: |
          git config --local user.joshua.plk08@gmail.com "EMAIL_GITHUB_KAMU"
          git config --local user.name "JoshNells13"
          git add .
          git commit -m "daily update" || echo "no changes"
          git push
